build_from:
  aarch64: docker.io/library/node:22-bookworm-slim
  amd64: docker.io/library/node:22-bookworm-slim
args:
  APP_REF: "54c513413958c8ef723e92dc7ca02689589cb074"
  YTDLP_VERSION: "2026.8.19"
